version: '3.1'

services:
  database:
    container_name: simplon_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'secret'
      # POSTGRES_USER: 'me'
      POSTGRES_DB: 'simplon'
    volumes: 
      - 'db:/var/lib/postgresql/data'
    ports: 
      - 5432:5432
  pgadmin: 
    container_name: simplon_pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: 'me@simplon.ma'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
    ports: 
      - '8080:80'
    volumes:
      - 'pgadmin:/var/lib/pgadmin'

volumes: 
  db: 
    driver: local
  pgadmin: 
    driver: local

